### ISSUE TITLE
impossible to change the column width by yourself

### ISSUE THREAD

**Issue by gadtwo** [knoxfighter/GW2-ArcDPS-Boon-Table#5] opened 2021-02-24 15:04 UTC
thanks for your job, and everything was done perfectly, but =)
there is no way to change the width of the column for each boon, which makes the window too large

**Comment by danifischer** [comment] 2021-02-24 17:49
+1 

I would also like to have the columns smaller, as the UI takes a lot of space.

**Comment by danifischer** [comment] 2021-02-24 17:50
I just saw that it is on your TODO (Duplicate of #2)

**Comment by hk3wx** [comment] 2021-02-24 23:52
A way to fix this is to set a MaxDisplayed in the same way Arcdps does.
That would be ideal.

**Comment by knoxfighter** [comment] 2021-04-12 19:08
Implemented with new release v2.1.0

**Closed by knoxfighter** 2021-04-12 19:08 UTC
Labels: enhancement
