### ISSUE TITLE
Total bar and UI 

### ISSUE THREAD

**Issue by Skarat148** [knoxfighter/GW2-ArcDPS-Boon-Table#4] opened 2021-02-24 11:26 UTC
Hello. 
Firstly, big thanks for your job. 
I saw, that you want to lock "self being 1st player in list". It would be great, if you lock Total bar at the window bottom aswell.
And about UI. 
It would be extremely good if you add option to change Boon windows size to be able to add other Boons without significantly expanding the overall window. Or just shrink current ones for about 50%
Thank you again man

**Comment by knoxfighter** [comment] 2021-02-25 02:48
You can disable the option "Always resize to content". And then you can change the size of the window by dragging the bottom right corner.

**Comment by Skarat148** [comment] 2021-02-25 07:34
I know about main window resize option. But i mean every single window inside main (name, sub and boons)

**Comment by knoxfighter** [comment] 2021-03-01 13:37
Duplicate of #5

**Closed by knoxfighter** 2021-03-01 13:37 UTC
Labels: enhancement
